---
version: '3.6'

services:
  BLOG_frontend_dev:
    container_name: '${BLOG_FRONTEND_NAME}'
    image: ${BLOG_FRONTEND_IMG}:${BLOG_FRONTEND_VERSION_DEV}
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 30s
    environment:
    - 'CHOKIDAR_USEPOLLING=true'
    - 'CHOKIDAR_INTERVAL'
    volumes:
    - ./src:/app:rw
    ports:
    - ${BLOG_FRONTEND_PORT}:8080
    restart: unless-stopped
